### ISSUE TITLE
ModuleNotFoundError: No module named 'xshade'

### ISSUE THREAD

**Issue by kaihux** [fastscape-lem/fastscape-demo#13]
When I ran the examples in the tutorial, the model ran well without a hitch. But two error messages popped out when I try to do the plotting: `ModuleNotFoundError: No module named 'hvplot'` & `ModuleNotFoundError: No module named 'xshade'`. I was able to pip install hvplot, but I don't know how to install xshade.

I installed the fastscape using `conda install fastscape -c conda-forge` , it should have installed all the dependencies.

**Comment by benbovy** [comment]
Hi @kaihux, sorry for the late reply.

`xshade` is a local python module in the `examples` folder, it has not been installed using pip or conda. You can copy the `xshade.py` file in the same folder than the notebooks that use it, though.

`conda install fastscape -c conda-forge` will not install all the packages used in this demo. It will only install the required dependencies to run fastscape, which doesn't include plotting libraries. You need to install the later explicitly, e.g.,  `conda install hvplot -c conda-forge`. You can have a look at the `environment.yml` file in this repository to see all the packages required to run the notebooks here.
