### ISSUE TITLE
Drainage area process not working

### ISSUE THREAD

**Issue by jeanbraun** [fastscape-lem/fastscape-demo#3]
@benbovy, I have difficulties accessing the process DrainageArea. Is it because I am using an outdated version of fastscape (I am at 0.1.0.alpha). See screenshot attached...
![Screenshot 2020-03-05 at 17 08 31](https://user-images.githubusercontent.com/29861121/76000842-9276f980-5f04-11ea-926a-e72dc4881b3e.jpg)

**Comment by benbovy** [comment]
Yes I should probably release another (alpha) version for less confusion.

In the meantime, you can install the development version (master branch) of fastscape, e.g., in a new conda environment by following the steps in the [README file](https://github.com/fastscape-lem/fastscape-demo/blob/master/README.md#how-to-run-the-notebooks).
