### ISSUE TITLE
ModuleNotFoundError: No module named 'datashader.geo'

### ISSUE THREAD

**Issue by Joeperdefloep** [fastscape-lem/fastscape-demo#9]
In the examples, when importing `xshade`, the above error is raised.  
Datashader version: `0.12.0`
In the Datashader [documentation](https://datashader.org/user_guide/Geography.html), it is smentioned that `hillshade` is provided in the `xarrar-spatial` package. 
according to [this notebook](https://github.com/makepath/xarray-spatial/blob/master/examples/user_guide/8_Remote_Sensing.ipynb), the `shade` function can be used in stead:
`from datashader.transfer_functions import shade` and then use that.
If I missed something that caused the error, please let me know!

**Comment by Gael-de-Sailly** [comment]
I'm running into the same issue. All packages installed via `conda` using the `environment.yml` provided. `datashader=0.12.0` as well.

I get the error at the end of the jupyter tutorials.

Full error message:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-1746b0450823> in <module>
      1 import hvplot.xarray
      2 import holoviews as hv
----> 3 from xshade import hillshade
      4 
      5 

~/Github/fastscape-demo/examples/xshade.py in <module>
----> 1 import datashader.geo as dgeo
      2 
      3 
      4 def hillshade(ds, groupby=None, elev_var='topography__elevation', **kwargs):
      5     elev = ds[elev_var]

ModuleNotFoundError: No module named 'datashader.geo'
```

**Comment by Joeperdefloep** [comment]
it seems to be related to [this issue](https://github.com/holoviz/datashader/issues/871) where `datashader.geo` is moved to xspatial. Should be easy t solve, I'll prepare a PR

**Comment by benbovy** [comment]
Thanks for the report!

@Joeperdefloep, unfortunately #10 will not look better because of a bug in `xarray-spatial.hillshade`. There are also other issues that need to be fixed upstream, so I pinned some of the dependencies in #11 as a temporary workaround.

**Comment by Joeperdefloep** [comment]
Thanks, yes I modified it in an environment where I had installed some other packages and then it worked, I closed the PR. (I think we can also close this issue now)
